# Generated by Django 3.2.8 on 2022-04-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0003_auto_20220424_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
