# Generated by Django 3.2.8 on 2022-04-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0004_auto_20220424_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_code',
            field=models.CharField(max_length=8),
        ),
    ]
